### ISSUE TITLE
libcapstone.so.4()(64bit)

### ISSUE THREAD

**Issue by gueniewie** [ladar/qemu-spice-el9#2]
Hello,
Thanks for your work, but i installed almalimux 9.1 and can't found libcapstone.so.4()(64bit) on any rpm, and so I have only ERRORS bei starting sh INSTALL.sh.

Can I found in any repos this file ?

Thanks for your help

**Comment by ladar** [comment]
I think the capstone RPMs were removed from EPEL because they'll be added to the official repos with RHEL 9.2. 

I'll rebuild the RPMs and include capstone with the upload.

**Comment by ladar** [comment]
@gueniewie a new set RPMs has been uploaded, which includes the capstone library. 

Hopefully, I'll remember to remove the capstone libs when RHEL 9.2 ships, .as my goal is to only provide RPMs which were either a) recompiled, or b) aren't available from the standard EL+EPEL repos.
